= Device Security Rating - Documentation

NOTE: This software is a proof of concept and is not intended for production use. It will not be maintained or receive updates. Concepts from this project will be used in gematik specifications to standardize Zero Trust in Telematics Infrastructure. Developers are encouraged to use the implementation ideas in their own software.

Device Security Rating (DSR) is a Proof of Concept to demonstrate the secure access to services using Zero Trust design principles. In contrast to enterprise-centric Zero Trust architectures, where devices need to be owned and/or managed by a company, the DSR PoC is designed in a way that allows participants from different legal and organisational entities without the need of giving up the ownership of their devices.

This repository contains the documentation for DSR Project as well as source for the landing page.

* https://dsr.gematik.solutions[Device Security Rating Landing Page] (https://github.com/gematik/poc-dsr-documentation/tree/hugo[Sources])
* https://github.com/gematik/poc-dsr-gms[Device Management Serivce (GMS)]
* https://github.com/gematik/poc-dsr-fd[Dummy Health Service (FD)]
* https://github.com/gematik/poc-dsr-fachdienst-policy[Dummy Health Service Policy (FD Policy)]
* https://github.com/gematik/poc-dsr-pep[Policy Enforcement Point (PEP)]
* https://github.com/gematik/ref-dsr-cpe-cve-matcher[Mobile Vulnerability Management (MVM)]
* https://github.com/gematik/poc-dsr-android[Android App / Trust Client (TCL)]
* https://github.com/gematik/poc-dsr-ios[iOS App / Trust Client (TCL)]
