@startuml DSR-RFC-03 Main Flow 
autonumber "<b>[00]"

actor User as User

User -> FrontEnd: view devices
FrontEnd -> TrustClient: request devices

TrustClient --> DMS++: establish mTLS channel (cert_mTLS)
TrustClient -> DMS: GET ""/device-registrations""\n\t""userIdentifier={KVNR}""
DMS -> TrustClient: array ""DeviceRegistration""
TrustClient -> FrontEnd: devices list
FrontEnd -> User: show devices
User -> FrontEnd: delete device_X
FrontEnd -> TrustClient: delete device_X
TrustClient --> DMS: DELETE ""/device-registrations""\n\t""userIdentifier={KVNR}""\n\t""deviceIdentifier={device_X}""
DMS --> TrustClient--: 200 OK
TrustClient -> FrontEnd: deleted successfully
FrontEnd -> User: show remaining devices

@enduml
